// import '@/pages/src/styles/globals.css'
import "@/styles/globals.css";

import Context from "./src/Context";
import NavBar from "./src/component/NavBar";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <Context>
      <Head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />

        <link rel="manifest" href="/manifest.json" />
        <link
          href="/favicon-16x16.png"
          rel="icon"
          type="image/png"
          sizes="16x16"
        />
        <link
          href="/favicon-32x32.png"
          rel="icon"
          type="image/png"
          sizes="32x32"
        />
        <link rel="apple-touch-icon" href="/apple-icon.png"></link>
        <meta name="theme-color" content="#317EFB" />

        <title>Create Next App</title>

        {/* <meta name="description" content="Generated by create next app; charSet=UTF-8" /> */}
        {/* <meta charset="UTF-8"></meta> */}

        <link rel="icon" href="free-sticker-rubber-duck-4861674.png" />
      </Head>
      <main>
        <Component {...pageProps} />
      </main>
      <NavBar />
      {/* 로그인 구현하고나면 지울예정 */}
    </Context>
  );
}
